### ISSUE TITLE
There is no output from console.log in my console when I use pino-toke

### ISSUE THREAD

**Issue by EdwardDiehl** [pinojs/pino-toke#1]
Hi @davidmarkclements 
I have `server` script like this in my `package.json` file
`"server": "app/server.js | pino-toke :method :url :status :res[content-length] - :response-time ms"`
Also I have `console.log('some data')` in several places in my code.
When I start the server I do not see the output in the console.

Is it supposed behavior? Thanks.

**Comment by mcollina** [comment]
You should use the `-a` switch, check https://github.com/pinojs/pino-toke#ancillary-output--a.

`pino-toke` automatically filters everything that is not pino logs.

**Comment by EdwardDiehl** [comment]
@mcollina thanks for your response

I tried these options:
`app/server.js | pino-toke -a 1 :method :url :status :res[content-length] - :response-time ms`
`app/server.js | pino-toke -a 2 :method :url :status :res[content-length] - :response-time ms`
`app/server.js | pino-toke -a stdout :method :url :status :res[content-length] - :response-time ms`
`app/server.js | pino-toke -a stderr :method :url :status :res[content-length] - :response-time ms`
`app/server.js | pino-toke -a 3 :method :url :status :res[content-length] - :response-time ms 3> ./logs`

Unfortunately still not see output of `console.log`, only http logs,
logs file was also empty.

**Comment by davidmarkclements** [comment]
hey @EdwardDiehl - so the `-a` flag is actually for specifying an output stream for original JSON messages (so you could send formatted logs to stdout and original JSON logs to stderr and then use bash redirection to store in separate files)

We're really expecting all log messages to be in newline JSON delimited format, if these a `console.logs` you want to keep in production when I would alter them to pino.info. If they have info that you're extracting with your specified token format, then do use the `-a` flag to store those richer JSON logs.

However, if you're just trying to insert console.logs for quick debugging etc, you could just use console.warn or console.error:

```sh
$ node -e "console.warn('hi')" | pino-toke :method :url :status
hi
```

If however you have console.log statements in lots of places, you could instead do something like

```
var console = new (require('console')).Console(process.stderr)
```

Then any `console.log` statements in scope of the `console` var will be sent to stderr

**Comment by EdwardDiehl** [comment]
I was just trying to insert `console.log` for quick debugging. I am not going to use `console.log` in many places in production.
I tried `console.warn` and works for this case.
Thanks @davidmarkclements for the explanation !
Then I'll close the issue.
