### ISSUE TITLE
[Bug] pino-toke output wrong time and date in case of using CLF format option

### ISSUE THREAD

**Issue by ryu-sato** [pinojs/pino-toke#2]
I found a bug that pino-toke output wrong time(and date) in case of using CLF format option.

How to reproduce?
---------------------------

1. Ready `express` with `express-pino-logger` which is same as example.
    - https://github.com/pinojs/express-pino-logger#example
1. Run `express` and pipe the output to `pino-toke`.
    ```bash
    $ node pino-toke-test.js | pino-toke :date[clf]
    ```
1. Access to `express`. (Client is in same host)
    ```bash
    $ curl -I localhost:3000
    ```

What happens?
---------------------

pino-toke output wrong access time in CLF format.

### access result

````bash
$ curl -I localhost:3000
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 11
ETag: W/"b-Kq5sNclPz7QV2+lfQIuc6R7oRu0"
Date: Sat, 21 Apr 2018 13:29:30 GMT
Connection: keep-alive
````

```bash
$ node pino-toke-test.js | ./node_modules/.bin/pino-toke :date[clf]
21/Apr/2018:13:29:30 -0540
$ date
Sat Apr 21 22:34:48 JST 2018
```

What is the expected result?
-------------------------------------------

- Output time and date correctly.

In this case, it is expected to output `21/Apr/2018:22:29:30 +0900`.
(ref. https://en.wikipedia.org/wiki/Common_Log_Format)

Note
----

- I was send PR to clf-date, because it seemed to the bug caused by clf-date. But no reply in a week. So I hope this community to correspond the bug.
https://github.com/lludol/clf-date/pull/7

**Comment by davidmarkclements** [comment]
Ok let's see if there's any movement in clf-date in the next couple days - if not would you be interested in forking clf-date with your patch and publishing to npm under a new name? If so I would be happy for pino-toke to depend on your fork

**Comment by ryu-sato** [comment]
Thanks for your quick reply.
There is no problem to create a new npm package.
If the bug is fixed, our application using pino-clf will be helpful too.

**Comment by ryu-sato** [comment]
@davidmarkclements Do you have any problem?

**Comment by ryu-sato** [comment]
@davidmarkclements 
lludol/clf-date#7 is closed.
Could you udpate clf-date from 0.1.0 to 0.2.0 ? (Please see: PR #6 )
Thanks.
